<a href="https://colab.research.google.com/github/AlgoAIBoss/University-Competition-First-place-code/blob/main/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, mean_absolute_error, f1_score, accuracy_score, confusion_matrix
from sklearn.model_selection import GridSearchCV, RepeatedStratifiedKFold
from sklearn.pipeline import Pipeline, make_pipeline, FeatureUnion
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split, RandomizedSearchCV
import pandas_profiling as pp
from pandas_profiling import ProfileReport
rng = np.random.RandomState(0)

In [ ]:

from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
# # Concatenate several csv files


# import glob
# import pandas as pd

# # get data file names
# path =r'/content/gdrive/MyDrive/Colab Notebooks/DM/TestData'
# filenames = glob.glob(path + "/*.csv")

# df = []
# for filename in filenames:
#     df.append(pd.read_csv(filename))

# # Concatenate all data into one DataFrame
# data = pd.concat(df, ignore_index=True)

In [ ]:
submission = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/DM/submission.csv')

In [ ]:
test = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/DM/TestData.csv')

In [ ]:
train = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/DM/Full.csv')

In [ ]:
data = pd.concat([test, train]).reset_index(drop=True)

# Checking

In [ ]:
test[test['lk1'] == test['lk2']]

In [ ]:
(train[(train['match_outcome'] == train['lk1lk2']) == False ]).head(50)

In [ ]:
(train[train['lk1'] != train['lk2']][(train['match_outcome'] == train['lk1lk2']) == False]).shape[0]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

102

In [ ]:
(train[train['lk1'] == train['lk2']][(train['match_outcome'] == train['lk1lk2']) == False]).shape[0]

In [ ]:
(train[train['lk1'] == train['lk2']][(train['match_outcome'] == train['lk1lk2']) == False]).shape[0] / (train[train['lk1'] == train['lk2']][(train['match_outcome'] != train['lk1lk2']) == False]).shape[0]

In [ ]:
test[test['similar_ratings'] == 1]

In [ ]:
(test[(test['match_outcome'] != test['lk1lk2']) == True])

    date_of_match  player1_id player1_name  ...  lk1_freq  lk2_freq  similar_ratings
11     2020-08-16    20802789     Nitzsche  ...  0.262195  0.060976                1
19     2020-12-07    20802789     Nitzsche  ...  0.262195  0.030488                0
22     2020-06-14    20802789     Nitzsche  ...  0.262195  0.006098                0
29     2020-02-02    20802789     Nitzsche  ...  0.262195  0.060976                1
44     2020-09-20    20556878   Grigorieva  ...  0.073171  0.006098                1
52     2020-12-01    20556878   Grigorieva  ...  0.073171  0.030488                0
58     2020-09-08    20800393      Khomich  ...  0.250000  0.006098                1
62     2020-02-08    20800393      Khomich  ...  0.250000  0.030488                0
66     2020-07-22    20800393      Khomich  ...  0.250000  0.042683                1
88     2020-06-01    20800393      Khomich  ...  0.250000  0.024390                0
93     2019-11-24    20800393      Khomich  ...  0.250000  0.024390                0
95     2019-11-17    20800393      Khomich  ...  0.250000  0.006098                0
102    2020-04-09    20750756      Ribbert  ...  0.140244  0.012195                0
111    2020-05-07    20750756      Ribbert  ...  0.140244  0.018293                1
113    2020-11-06    20750756      Ribbert  ...  0.140244  0.030488                0
119    2020-09-20    20800243      Wächter  ...  0.274390  0.006098                0
124    2020-08-23    20800243      Wächter  ...  0.274390  0.042683                1
125    2020-08-23    20800243      Wächter  ...  0.274390  0.024390                1
142    2020-08-03    20800243      Wächter  ...  0.274390  0.006098                0
152    2020-01-26    20800243      Wächter  ...  0.274390  0.042683                1
156    2020-04-01    20800243      Wächter  ...  0.274390  0.024390                0
160    2019-08-12    20800243      Wächter  ...  0.274390  0.042683                1
163    2019-11-23    20800243      Wächter  ...  0.274390  0.042683                1

[23 rows x 21 columns]

In [ ]:
(test[test['lk1'] != test['lk2']][(test['match_outcome'] != test['lk1lk2']) == False])

In [ ]:
(train[train['lk1-lk2'] == 0.0]).shape

(50, 21)

In [ ]:
test[test['similar_ratings'] == True].shape

(3, 21)

In [ ]:
accuracy_score(test['match_outcome'], test['lk1lk2'])

0.8597560975609756

In [ ]:
test.head(50)

   date_of_match  player1_id player1_name  ...  lk1_freq  lk2_freq  similar_ratings
0     2020-09-20    20802789     Nitzsche  ...  0.262195  0.042683                0
1     2020-09-20    20802789     Nitzsche  ...  0.262195  0.036585                0
2     2020-09-13    20802789     Nitzsche  ...  0.262195  0.006098                0
3     2020-09-13    20802789     Nitzsche  ...  0.262195  0.012195                0
4     2020-09-13    20802789     Nitzsche  ...  0.262195  0.006098                0
5     2020-12-09    20802789     Nitzsche  ...  0.262195  0.060976                0
6     2020-08-30    20802789     Nitzsche  ...  0.262195  0.006098                0
7     2020-08-30    20802789     Nitzsche  ...  0.262195  0.006098                0
8     2020-08-30    20802789     Nitzsche  ...  0.262195  0.006098                0
9     2020-08-30    20802789     Nitzsche  ...  0.262195  0.012195                0
10    2020-08-16    20802789     Nitzsche  ...  0.262195  0.006098                0
11    2020-08-16    20802789     Nitzsche  ...  0.262195  0.060976                0
12    2020-08-13    20802789     Nitzsche  ...  0.262195  0.018293                0
13    2020-08-13    20802789     Nitzsche  ...  0.262195  0.006098                0
14    2020-08-13    20802789     Nitzsche  ...  0.262195  0.024390                0
15    2020-09-08    20802789     Nitzsche  ...  0.262195  0.030488                0
16    2020-09-08    20802789     Nitzsche  ...  0.262195  0.030488                0
17    2020-02-08    20802789     Nitzsche  ...  0.262195  0.060976                0
18    2020-02-08    20802789     Nitzsche  ...  0.262195  0.012195                0
19    2020-12-07    20802789     Nitzsche  ...  0.262195  0.030488                0
20    2020-12-07    20802789     Nitzsche  ...  0.262195  0.012195                0
21    2020-05-07    20802789     Nitzsche  ...  0.262195  0.060976                0
22    2020-06-14    20802789     Nitzsche  ...  0.262195  0.006098                0
23    2020-06-14    20802789     Nitzsche  ...  0.262195  0.006098                0
24    2020-06-14    20802789     Nitzsche  ...  0.262195  0.012195                0
25    2020-01-03    20802789     Nitzsche  ...  0.262195  0.012195                0
26    2020-09-02    20802789     Nitzsche  ...  0.262195  0.006098                0
27    2020-02-02    20802789     Nitzsche  ...  0.262195  0.024390                0
28    2020-02-02    20802789     Nitzsche  ...  0.262195  0.030488                0
29    2020-02-02    20802789     Nitzsche  ...  0.262195  0.060976                0
30    2020-02-02    20802789     Nitzsche  ...  0.262195  0.024390                0
31    2020-01-26    20802789     Nitzsche  ...  0.262195  0.018293                0
32    2020-01-26    20802789     Nitzsche  ...  0.262195  0.006098                0
33    2020-01-26    20802789     Nitzsche  ...  0.262195  0.006098                0
34    2020-12-01    20802789     Nitzsche  ...  0.262195  0.042683                0
35    2020-12-01    20802789     Nitzsche  ...  0.262195  0.006098                0
36    2020-12-01    20802789     Nitzsche  ...  0.262195  0.018293                0
37    2020-12-01    20802789     Nitzsche  ...  0.262195  0.030488                0
38    2020-06-01    20802789     Nitzsche  ...  0.262195  0.042683                0
39    2019-12-31    20802789     Nitzsche  ...  0.262195  0.006098                0
40    2019-12-31    20802789     Nitzsche  ...  0.262195  0.024390                0
41    2019-12-29    20802789     Nitzsche  ...  0.262195  0.006098                0
42    2019-12-29    20802789     Nitzsche  ...  0.262195  0.006098                0
43    2020-09-20    20556878   Grigorieva  ...  0.073171  0.006098                0
44    2020-09-20    20556878   Grigorieva  ...  0.073171  0.006098                0
45    2020-09-13    20556878   Grigorieva  ...  0.073171  0.012195                0
46    2020-12-07    20556878   Grigorieva  ...  0.073171  0.024390                0
47    2020-06-20    20556878   Grigorieva  ...  0.073171  0.042683                0
48    2020-08-03    20556878   Grigorieva  ...  0.073171  0.012195                0
49    2020-01-26    20556878   Grigorieva  ...  0.073171  0.018293                0

[50 rows x 21 columns]

In [ ]:
t.head()

  date_of_match  player1_id player1_name  ...  lk1_freq  lk2_freq  similar_ratings
0    2020-09-06    26852620  Hildenbrand  ...       1.0  0.041667                0
1    2020-09-01    26852620  Hildenbrand  ...       1.0  0.041667                0
2    2020-09-01    26852620  Hildenbrand  ...       1.0  0.125000                0
3    2020-08-23    26852620  Hildenbrand  ...       1.0  0.083333                0
4    2020-08-23    26852620  Hildenbrand  ...       1.0  0.041667                0

[5 rows x 21 columns]

# Drop Duplicates

In [ ]:
data.drop_duplicates(subset=['date_of_match', 'player2_id', 'lk2'], keep='first', inplace=True)

In [ ]:
data[data.duplicated()]

# drop "match_outcome"

In [ ]:
submission.head()

  player1_name player2_name  ...    Voting Voting_Accuracy
0     Nitzsche        Galow  ...  gewonnen             92%
1     Nitzsche        Seitz  ...  gewonnen             92%
2     Nitzsche         Giza  ...  verloren             92%
3     Nitzsche          Ebs  ...  gewonnen             92%
4     Nitzsche       Adamus  ...  gewonnen             92%

[5 rows x 62 columns]

In [ ]:
Feature_names = submission.select_dtypes('int')

In [ ]:
Feature_names.columns.astype('str')

Index(['CatBoost', 'Logistic Regression', 'Random Forest', 'KNeighbors', 'SVC',
       'ExtraTrees', 'MLPClassifier', 'GradientBoosting', 'DecisionTree',
       'XGBoost', 'LightGBM', 'XGBM_Bagging', 'LGBM_Bagging', 'KNN_Bagging',
       'LR_Bagging', 'RF_Bagging', 'SVC_Bagging', 'GBC_Bagging', 'EXT_Bagging',
       'DT_Bagging', 'MLP_Bagging', 'DT_Boosting', 'LGBM_Boosting',
       'LR_Boosting', 'RF_Boosting', 'SVC_Boosting', 'GBC_Boosting',
       'EXT_Boosting', 'Stacking', 'Voting'],
      dtype='object')

In [ ]:
x = []

for each in Feature_names.columns.astype('str'):
  x.append(each)
  #submission = submission.replace({each:{'verloren':0, 'gewonnen':1}})

In [ ]:
for each in x:
  submission = submission.replace({each:{0:'verloren', 1:'gewonnen'}})

In [ ]:
submission = submission.replace({'match_outcome':{'verloren':0, 'gewonnen':1}})

In [ ]:
X = data.drop('match_outcome', axis=1)
y = data.match_outcome

In [ ]:
X

# delete 'score'

In [ ]:
del data['score']

# Datetime EDA

In [ ]:
test['date_of_match']= pd.to_datetime(test['date_of_match'])

In [ ]:
#extracting Date values to columns month day year

test['month'] = test['date_of_match'].dt.month
test['day'] = test['date_of_match'].dt.day
test['year'] = test['date_of_match'].dt.year
test['quarter'] = test['date_of_match'].dt.quarter
#data['semester'] = np.where(data.quarter.isin([1,2]),1,2)
test['dayofweek'] = test['date_of_match'].dt.dayofweek
test['dayofweek_name'] = test['date_of_match'].dt.day_name()

#(datetime.datetime.today() - data['date_of_match']).head()

# "lk1lk2" 1 if difference is positive else 0

In [ ]:
test['lk1lk2'] = test.lk1 - test.lk2


test['lk1lk2'] = np.where(test['lk1-lk2'] < 0, 1, 0).tolist()

# lk1-lk2

In [ ]:
test['lk1-lk2'] = test.lk1 - test.lk2

In [ ]:
test['lk1-lk2'] = np.where(test['lk1-lk2'] == 0.0, 1, test['lk1-lk2']).tolist()

# "time_diff"  put 1 if the match happened in the same day

In [ ]:
test['time_diff'] = test.day
a = np.array(test['time_diff'].values.tolist())
test['time_diff'] = np.where(test['date_of_match'].dt.day.diff().eq(0) == True, 1, 0).tolist()

# "lk2_freq" and "lk1_freq"

In [ ]:
color_encode = (test.groupby('lk1').size()) / len(test)

test['lk1_freq'] = test['lk1'].apply(lambda x : color_encode[x])


color_encode = (test.groupby('lk2').size()) / len(test)

test['lk2_freq'] = test['lk2'].apply(lambda x : color_encode[x])

# weekend if 5 or 6 put 1 else 0

In [ ]:
test['weekend'] = np.where(test['dayofweek_name'].isin(['Sunday','Saturday']),1,0)

# "rate_error"

In [ ]:
# raplace negative values with 0 and positive with 1
data['rate_error'] = data.day
a = np.array(data['rate_error'].values.tolist())
data['rate_error'] = np.where(((data['match_outcome'] == data['lk1lk2']) == False) == True, 1, 0).tolist()

# Convert to Category

In [ ]:
test[['player1_name', 'player2_name', 'dayofweek_name','date_of_match']] = test[['player1_name', 'player2_name', 'dayofweek_name', 'date_of_match']].astype('category')

In [ ]:
test.dtypes

date_of_match      datetime64[ns]
player1_id                  int64
player1_name               object
player2_id                  int64
player2_name               object
match_outcome               int64
lk1                       float64
lk2                       float64
month                       int64
day                         int64
year                        int64
quarter                     int64
dayofweek                   int64
dayofweek_name             object
weekend                     int64
time_diff                   int64
lk1-lk2                   float64
lk1lk2                      int64
lk1_freq                  float64
lk2_freq                  float64
similar_ratings             int64
dtype: object



---

# Check if Rating is the same

---

In [ ]:
test[test['lk1'] == test['lk2']]

# Or

#train[train['lk1-lk2'] == 0]

In [ ]:
train['lk1lk2'] = np.where(((train['lk1'] == train['lk2']) == True) == True, 1, train['lk1lk2']).tolist()



---

# Cinfirm equal retings are missing in lk1lk2

---

In [ ]:
train[train['lk1'] == train['lk2']][(train['match_outcome'] == train['lk1lk2']) == False]

In [ ]:
(train[train['lk1'] == train['lk2']][(train['match_outcome'] == train['lk1lk2']) == False]).value_counts()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

date_of_match  player1_id  player1_name  player2_id  player2_name  match_outcome  lk1   lk2   month  day  year  quarter  dayofweek  dayofweek_name  weekend  time_diff  lk1-lk2  lk1lk2  lk1_freq  lk2_freq  similar_ratings
2020-12-07     20651971    Menze         20655479    Ukic          1              11.7  11.7  12     7    2020  4        0          Monday          0        0          0.0      0       0.295455  0.022727  1                  1
2020-11-01     20550631    Volkov        29000187    Döring        1              1.5   1.5   11     1    2020  4        6          Sunday          1        0          0.0      0       0.285088  0.263158  1                  1
2019-11-10     20550631    Volkov        20350627    Nizetic       1              1.5   1.5   11     10   2019  4        6          Sunday          1        1          0.0      0       0.285088  0.263158  1                  1
2019-11-23     20550631    Volkov        20350624    Beßer         1              1.5   1.5   11     23   2019  4        5          Saturday        1        0          0.0      0       0.285088  0.263158  1                  1
                                         20350627    Nizetic       1              1.5   1.5   11     23   2019  4        5          Saturday        1        1          0.0      0       0.285088  0.263158  1                  1
2019-12-01     20354473    Wood          20651357    Thies         1              20.1  20.1  12     1    2019  4        6          Sunday          1        1          0.0      0       0.057018  0.026316  1                  1
               20550631    Volkov        20551981    Schmid        1              1.5   1.5   12     1    2019  4        6          Sunday          1        1          0.0      0       0.285088  0.263158  1                  1
2019-12-15     20651370    Wolter        20461571    Wagner        1              12.1  12.1  12     15   2019  4        6          Sunday          1        1          0.0      0       0.176707  0.028112  1                  1
2019-12-22     20550631    Volkov        20550009    Nemeth        1              1.5   1.5   12     22   2019  4        6          Sunday          1        1          0.0      0       0.285088  0.263158  1                  1
               20558157    Ruhe          20750070    Blaschke      1              15.1  15.1  12     22   2019  4        6          Sunday          1        1          0.0      0       0.175439  0.030702  1                  1
2019-12-28     20653781    Seidelmann    20301524    Nogossek      1              6.1   6.1   12     28   2019  4        5          Saturday        1        1          0.0      0       0.219298  0.030702  1                  1
2019-12-31     20801184    Sachenko      20557711    Schaudinn     1              13.1  13.1  12     31   2019  4        1          Tuesday         0        0          0.0      0       0.192771  0.044177  1                  1
2020-01-18     20550631    Volkov        29650168    Halfmann      1              1.5   1.5   1      18   2020  1        5          Saturday        1        0          0.0      0       0.285088  0.263158  1                  1
2020-05-09     20754594    Fischer       20457747    Goedecke      1              15.1  15.1  5      9    2020  2        5          Saturday        1        0          0.0      0       0.238636  0.102273  1                  1
2020-05-24     20550631    Volkov        20250259    Chistov       1              1.5   1.5   5      24   2020  2        6          Sunday          1        0          0.0      0       0.285088  0.263158  1                  1
2020-06-15     20550631    Volkov        28509362    Dörnemann     1              1.5   1.5   6      15   2020  2        0          Monday          0        0          0.0      0       0.285088  0.263158  1                  1
2020-06-21     20801184    Sachenko      20652016    Kolks         1              13.1  13.1  6      21   2020  2        6          Sunday          1        1          0.0      0       0.192771  0.044177  1                  1
2020-06-28     20550631    Volkov        29301184    Köhler        1              1.5   1.5   6      28   2020  2        6          Sunday          1        0          0.0      0       0.285088  0.263158  1                  1
2020-07-19     20550631    Volkov        27905041    Löchter       1              1.5   1.5   7      19   2020  3        6          Sunday          1        1          0.0      0       0.285088  0.263158  1                  1
2020-08-05     20455145    Kopp          20150510    Harms         1              7.1   7.1   8      5    2020  3        2          Wednesday       0        1          0.0      0       0.096491  0.026316  1                  1
2020-08-15     20550631    Volkov        20550071    Abdou         1              1.5   1.5   8      15   2020  3        5          Saturday        1        0          0.0      0       0.285088  0.263158  1                  1
2020-08-23     20800243    Wächter       20803061    Bodea         1              15.0  15.0  8      23   2020  3        6          Sunday          1        1          0.0      0       0.180723  0.044177  1                  1
2020-08-30     20801184    Sachenko      20652016    Kolks         1              13.1  13.1  8      30   2020  3        6          Sunday          1        0          0.0      0       0.192771  0.044177  1                  1
2020-09-07     20754594    Fischer       20551904    Bodem         1              15.1  15.1  9      7    2020  3        0          Monday          0        1          0.0      0       0.238636  0.102273  1                  1
2020-09-12     20550631    Volkov        20551279    Jurina        1              1.5   1.5   9      12   2020  3        5          Saturday        1        0          0.0      0       0.285088  0.263158  1                  1
2020-09-14     20550631    Volkov        20450674    Eberwein      1              1.5   1.5   9      14   2020  3        0          Monday          0        0          0.0      0       0.285088  0.263158  1                  1
2020-09-27     20550631    Volkov        20250666    Bögner        1              1.5   1.5   9      27   2020  3        6          Sunday          1        1          0.0      0       0.285088  0.263158  1                  1
                                         29101055    Schwarzer     1              1.5   1.5   9      27   2020  3        6          Sunday          1        1          0.0      0       0.285088  0.263158  1                  1
               20754594    Fischer       29753705    Pfau          1              15.1  15.1  9      27   2020  3        6          Sunday          1        0          0.0      0       0.238636  0.102273  1                  1
2019-10-13     20550631    Volkov        20450162    Menßen        1              1.5   1.5   10     13   2019  4        6          Sunday          1        1          0.0      0       0.285088  0.263158  1                  1
dtype: int64

In [ ]:
test[test['lk1'] == test['lk2']]

   date_of_match  player1_id player1_name  ...  lk1lk2  lk1_freq  lk2_freq
22    2020-12-07    20651971        Menze  ...       1  0.295455  0.022727
39    2020-09-27    20754594      Fischer  ...       1  0.238636  0.102273
41    2020-05-09    20754594      Fischer  ...       1  0.238636  0.102273
46    2020-09-07    20754594      Fischer  ...       1  0.238636  0.102273

[4 rows x 20 columns]



---

# Check missingness in "lk1lk2" through lk1-lk2

---

In [ ]:
(test[(test['match_outcome'] == test['lk1lk2']) == False ])

In [ ]:
train[(train['lk1-lk2'] < 0.30000000000000004) & (train['lk1-lk2'] > -0.30000000000000004) & (train['match_outcome'] != train['lk1lk2'])]

In [ ]:
(test[(test['lk1-lk2'] < 0.30000000000000004) & (test['lk1-lk2'] > -0.30000000000000004)])

In [ ]:
((test[(test['lk1-lk2'] < 0.30000000000000004) & (test['lk1-lk2'] > -0.30000000000000004) & (test['match_outcome'] != test['lk1lk2'])]).shape[0] / (test[(test['lk1-lk2'] < 0.30000000000000004) & (test['lk1-lk2'] > -0.30000000000000004)]).shape[0])*100

In [ ]:


y = []
x = []

for t in np.arange(0.1, 10, 0.1):
  answer = ((test[(test['lk1-lk2'] < t) & (test['lk1-lk2'] > -t) & (test['match_outcome'] != test['lk1lk2'])]).shape[0] / (test[(test['lk1-lk2'] < t) & (test['lk1-lk2'] > -t)]).shape[0])*100
  y.append(answer)
  x.append(t)

In [ ]:
train.loc[(train['lk1-lk2'] < 0.30000000000000004) & (train['lk1-lk2'] > -0.30000000000000004) & (train['match_outcome'] != train['lk1lk2']), 'lk1lk2']

In [ ]:
train['similar_ratings'] = train.day


train['similar_ratings'] = np.where((((train['lk1-lk2'] <= 1.1) & (train['lk1-lk2'] >= -1.1) & (train['match_outcome'] != train['lk1lk2'])) == True) == True, 1, 0).tolist()



---

# Save

---

In [ ]:
# save the cleaned data
submission.to_csv('/content/gdrive/MyDrive/Colab Notebooks/DM/submission.csv', index=False)

In [ ]:
test